puts " The members list of the Atlas community"
puts "---------------"
puts "Charles De Barros"
puts "Damien Hogan"
puts "Dharmesh Raithatha"
puts "Enrique Comba"
puts "Gavin Cooper"
puts "James Jenkins"
puts "Juan Manuel"
puts "Kurmaran"
puts "Robert Johnson"
puts "Ron Blanco"
puts "Ruben Kostucki"
puts "Sam Joseph"
puts "Samantha Harris"
puts "David Thompson"
puts "Joan Senent"
print "Overall, we have "
print 15
puts " great members"